geofield_map.settings:
  type: config_object
  label: 'Geofield Map settings'
  mapping:
    gmap_api_key:
      type: string
      label: 'Google Maps API Key'
    geocoder:
      type: config_object
      label: 'Geocoder settings'
      mapping:
        min_terms:
          type: integer
          label: 'The minimum terms for the Geocoder to start processing'
        delay:
          type: integer
          label: 'The delay in milliseconds between when a keystroke occurs and when a Geocode search is performed'
        options:
          type: string
          label: 'Geocoders/plugins Specific Options'
        plugins:
          type: sequence
          label: 'The enabled Geocoder Plugins'
          sequence:
            type: string
            label: "The Geocoder Plugin name"
        plugins_checkboxes:
          type: sequence
          label: 'The available Geocoder Plugins selection and options'
          sequence:
            type: config_object
            label: "The Geocoder Plugin Selection, Weight and Options"
            mapping:
              checked:
                type: string
                label: 'The Checkbox value'
              weight:
                type: string
                label: 'The Weight value'
              options:
                type: config_object
                label: 'The Geocoder Options'
                mapping:
                  gmap_api_key:
                    type: string
                    label: 'Google Maps API Key'
                  json_options:
                    type: string
                    label: 'The geocoder options data in json format'

