geofield_map.settings:
  type: config_object
  label: 'Geofield Map settings'
  mapping:
    gmaps_api_key:
      type: string
      label: 'Google Maps API Key'
    geocoder:
      type: config_object
      label: 'Geocoder settings'
      mapping:
        min_terms:
          type: integer
          label: 'The minimum terms for the Geocoder to start processing'
        delay:
          type: integer
          label: 'The delay in milliseconds between when a keystroke occurs and when a Geocode search is performed'
        options:
          type: string
          label: 'Geocoders/plugins Specific Options'